schema_version: 1

context:
  version: "1.1.3"

package:
  name: libpostal
  version: ${{ version }}

source:
  url: https://github.com/openvenues/libpostal/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 02883c2f62658a09f9e49819f7983c7b19a574f9422424ecd5e4ff43cf7830a8

build:
  number: 1
  skip: win
  script:
    file: build.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - curl
    - libtool
    - make
  run:
    - curl

tests:
  - script:
      - test -d ${PREFIX}/share/libpostal_data
      - test -d ${PREFIX}/share/libpostal_data/libpostal/address_expansions
      - test -d ${PREFIX}/share/libpostal_data/libpostal/address_parser
      - test -d ${PREFIX}/share/libpostal_data/libpostal/transliteration
      - test -f ${PREFIX}/share/libpostal_data/libpostal/transliteration/transliteration.dat
      - test -f ${PREFIX}/share/libpostal_data/libpostal/address_parser/address_parser_crf.dat
      - test -f ${PREFIX}/share/libpostal_data/libpostal/address_expansions/address_dictionary.dat
      - test -f ${PREFIX}/bin/libpostal_data
      - test -f $PREFIX/lib/libpostal${SHLIB_EXT}
  - script: test.sh

about:
  license: MIT
  license_file: LICENSE
  summary: C library for parsing/normalizing street addresses around the world.
  homepage: https://github.com/openvenues/libpostal

extra:
  recipe-maintainers:
    - MichaelMarien
    - tdsmith
